/**
 * Program Schedule block (radplapag/schedule).
 *
 * Displays the weekly program schedule for a selected radio station.
 * Dynamic block: save returns null; output is generated by PHP render_callback.
 *
 * @package radio-player-page
 * @since 3.3.0
 */

import { registerBlockType } from '@wordpress/blocks';
import { useBlockProps, InspectorControls } from '@wordpress/block-editor';
import { SelectControl, PanelBody } from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import ServerSideRender from '@wordpress/server-side-render';

import metadata from '../block.json';

const blockName = metadata.name;

function Edit( { attributes, setAttributes } ) {
	const { stationIndex } = attributes;
	const blockProps = useBlockProps();
	const stations = window.radplapagScheduleBlock?.stations || [];
	const options =
		stations.length === 0
			? [ { label: __( 'No stations configured', 'radio-player-page' ), value: 0 } ]
			: stations.map( ( station, index ) => ( {
					label: station.label || __( 'Station', 'radio-player-page' ) + ' ' + ( index + 1 ),
					value: index,
			  } ) );
	const safeIndex = Math.max( 0, Math.min( stationIndex, stations.length ? stations.length - 1 : 0 ) );

	return (
		<>
			<InspectorControls>
				<PanelBody title={ __( 'Schedule settings', 'radio-player-page' ) } initialOpen={ true }>
					<SelectControl
						label={ __( 'Station', 'radio-player-page' ) }
						value={ safeIndex }
						options={ options }
						onChange={ ( value ) => setAttributes( { stationIndex: parseInt( value, 10 ) } ) }
					/>
				</PanelBody>
			</InspectorControls>
			<div { ...blockProps }>
				<ServerSideRender block={ blockName } attributes={ { stationIndex: safeIndex } } />
			</div>
		</>
	);
}

registerBlockType( blockName, {
	...metadata,
	edit: Edit,
	save: () => null,
} );
