/**
 * Programs List block (radplapag/programs-list).
 *
 * Displays all programs for a selected radio station with name, image, extended description, and schedule.
 * Dynamic block: save returns null; output is generated by PHP render_callback.
 *
 * @package radio-player-page
 * @since 3.3.0
 */

import { registerBlockType } from '@wordpress/blocks';
import { useBlockProps, InspectorControls } from '@wordpress/block-editor';
import { SelectControl, PanelBody, ToggleControl } from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import ServerSideRender from '@wordpress/server-side-render';

import metadata from '../block.json';

const blockName = metadata.name;

function Edit( { attributes, setAttributes } ) {
	const { stationIndex, showImage, showDescription, showExtendedDescription, showSchedule } = attributes;
	const blockProps = useBlockProps();
	const stations = window.radplapagProgramsListBlock?.stations || [];
	const options =
		stations.length === 0
			? [ { label: __( 'No Radio Stations configured', 'radio-player-page' ), value: 0 } ]
			: stations.map( ( station, index ) => ( {
					label: station.label || __( 'Radio Station', 'radio-player-page' ) + ' ' + ( index + 1 ),
					value: index,
			  } ) );
	const safeIndex = Math.max( 0, Math.min( stationIndex, stations.length ? stations.length - 1 : 0 ) );
	const showImageValue = showImage !== false;
	const showDescriptionValue = showDescription !== false;
	const showExtendedDescriptionValue = showExtendedDescription !== false;
	const showScheduleValue = showSchedule !== false;

	return (
		<>
			<InspectorControls>
				<PanelBody title={ __( 'Radio Shows List Settings', 'radio-player-page' ) } initialOpen={ true }>
					<SelectControl
						label={ __( 'Radio Station', 'radio-player-page' ) }
						value={ safeIndex }
						options={ options }
						onChange={ ( value ) => setAttributes( { stationIndex: parseInt( value, 10 ) } ) }
					/>
					<ToggleControl
						label={ __( 'Show Image', 'radio-player-page' ) }
						checked={ showImageValue }
						onChange={ ( value ) => setAttributes( { showImage: value } ) }
					/>
					<ToggleControl
						label={ __( 'Show Description', 'radio-player-page' ) }
						checked={ showDescriptionValue }
						onChange={ ( value ) => setAttributes( { showDescription: value } ) }
					/>
					<ToggleControl
						label={ __( 'Show Extended Description', 'radio-player-page' ) }
						checked={ showExtendedDescriptionValue }
						onChange={ ( value ) => setAttributes( { showExtendedDescription: value } ) }
					/>
					<ToggleControl
						label={ __( 'Show Radio Schedule', 'radio-player-page' ) }
						checked={ showScheduleValue }
						onChange={ ( value ) => setAttributes( { showSchedule: value } ) }
					/>
				</PanelBody>
			</InspectorControls>
			<div { ...blockProps }>
				<ServerSideRender
					block={ blockName }
					attributes={ {
						stationIndex: safeIndex,
						showImage: showImageValue,
						showDescription: showDescriptionValue,
						showExtendedDescription: showExtendedDescriptionValue,
						showSchedule: showScheduleValue,
					} }
				/>
			</div>
		</>
	);
}

registerBlockType( blockName, {
	...metadata,
	edit: Edit,
	save: () => null,
} );
