/**
 * Now Playing block (radplapag/now-playing).
 *
 * Displays the radio show currently on air for a selected station, with schedule, and the
 * next show starting within 10 minutes.
 * Dynamic block: output is generated by render.php (wired via the "render" key in block.json),
 * so no save() is needed here.
 *
 * @package radio-player-page
 * @since 3.4.0
 */

import { registerBlockType } from "@wordpress/blocks";

import Edit from "./edit";
import metadata from "../block.json";

registerBlockType(metadata.name, {
  edit: Edit,
});
